### ISSUE TITLE
Why you using custom rustfmt config?

### ISSUE THREAD

**Issue by MedzikUser** [revanced/revanced-discord-bot#10]
In my opinion default config is better.

btw

![image](https://user-images.githubusercontent.com/87065584/178121267-91823fa7-a6e1-4809-a03f-1d214f5c269e.png)

**Comment by oSumAtrIX** [comment]
If there is a reason to switch please explain it

**Comment by MedzikUser** [comment]
> If there is a reason to switch please explain it

by example some features in this custom config is from nightly version

and in my opinion if you use rust then to make it easier for other people to contribute to the code then to use global rust formatting (default rustfmt config) which is the same in most projects

**Comment by oSumAtrIX** [comment]
In that case you can PR a fix for this.

**Comment by JelNiSlaw** [comment]
## Why would you do that?!

1. `rustfmt` is highly opinionated. That means almost everything is already decided for you. You can't change the code style (as in not use the "official Rust style") just by adding the config file.
2. `rustfmt.toml` is used for adding stricter formatting rules, like defining how imports are grouped and sorted. By removing these rules you didn't make the style "more Rust'y" — you've just made it more undefined and random.
3. If you don't use Rust nightly by default but still want to correctly format your code, run `cargo fmt +nightly`.

I recommend adding `rustfmt.toml` back (after more discussion), maybe without `hard_tabs`, as spaces are used for alignment in Rust, and mixed indentation is a pain.

**Comment by oSumAtrIX** [comment]
@JelNiSlaw please open an issue for discussion, thanks
