### ISSUE TITLE
Restore the `rustfmt.toml` file

### ISSUE THREAD

**Issue by JelNiSlaw** [revanced/revanced-discord-bot#13]
## `rustfmt.toml` was removed in #12

I do not agree with that decision. I listed my points in https://github.com/revanced/revanced-discord-bot/issues/10#issuecomment-1181595106.

**Comment by oSumAtrIX** [comment]
What is the problem with the default one? Doesn't it format according a standard too?

**Comment by JelNiSlaw** [comment]
The removed config:
- replaced CRLF line endings with LF,
- formatted code examples in docs (if any),
- grouped and sorted imports,
- used consistent comment formatting,
- and much more.

As you can see, by removing the config, the standard style is less enforced.

**Comment by JelNiSlaw** [comment]
I can PR a new config and explain the purpose of each rule if you want.

**Comment by oSumAtrIX** [comment]
> I can PR a new config and explain the purpose of each rule if you want.

Please suggest in #14.
