### ISSUE TITLE
feat: embeds for thread introductions

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-discord-bot#24]
## 🐞 Issue

Thread introductions do not support embeds.

## ❗ Solution

Thread introductions should support embeds and regular messages.

## ❓ Motivation

Currently, the bot uses embeds for every response in the ReVanced configuration. For completeness and consistency, this should also be the case for thread introductions.

**Comment by Ushie** [comment]
No longer needed
