### ISSUE TITLE
Discord authorization token validation

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-discord-bot#4]
# Issue

Validating the Discord authorization token like this is error-prone:
https://github.com/revanced/revanced-discord-bot/blob/25d343dfa53e12ed09489351afd00ec217adce56/src/main.rs#L237

# Solution

Instead, either a proper validation via a regular expression should be made, or no validation.

# Motivation

Iirc, serenity validates it already, hence I think it is not necessary to additionally validate the token.

**Comment by Sculas** [comment]
This was removed in ba7b82a6de3624ad59b587fa52ee784c3f2c9cf8.
