### ISSUE TITLE
A condition must be provided, or else the bot will crash

### ISSUE THREAD

**Issue by Sculas** [revanced/revanced-discord-bot#6]
Currently, every field in the config is required. If that is not satisfied, the bot will crash.

**Comment by oSumAtrIX** [comment]
This was the intended design. For example, here we allowed fields to be empty:
https://github.com/revanced/revanced-discord-bot/blob/88b50def737e2455166e623d3a2374eed4809cea/src/model/application.rs#L83

This can be changed.
