### ISSUE TITLE
 Add ?lock command 

### ISSUE THREAD

**Issue by xDARKxDEVILx** [ReVanced/revanced-discord-bot#75]
## 🐞 Issue
Currently there is no ?lock command just like there is a ?close one

## ❗ Solution
add ?lock command to lock posts in support 

## ❓ Motivation
Currently some people just like to complain about getting errors in someone else's post and they are not the same error so they should make their own post and it gets really messy to help people with different problems in the same post, so what i would do is to tell them to make different posts for their issue and to lock the post so they follow the order ¯\_(ツ)_/¯

Another reason to lock posts is when they do not follow the pinned post and make posts that is worth locking, like effortless posts or unrelated to ReVanced posts so i give them quick instructions on what to do and lock and close the post

There are other reasons to lock posts but i think they are known 

## ⚠ Additional context

I know i can just exit the post then long tab and lock it but that takes way more time and adding the lock command should be easy and useful anyway

**Comment by oSumAtrIX** [comment]
It already exists in the form of a autoresponder:

https://github.com/ReVanced/revanced-discord-bot/blob/main/configuration.example.json#L42-L46

**Comment by oSumAtrIX** [comment]
No, it can be configured to lock or close or both when you type anything that matches the regex provided such as "?lock".

**Comment by Ushie** [comment]
In that case, can we add that to our configuration?

**Comment by oSumAtrIX** [comment]
It is already present: https://github.com/ReVanced/revanced-discord-bot/blob/main/configuration.revanced.json#L319.
It is set to close because otherwise nobody will be able to comment in it again and would create a dupe post.
