### ISSUE TITLE
bug: names starting with numbers get cured

### ISSUE THREAD

**Issue by PalmDevs** [ReVanced/revanced-discord-bot#76]
## 🐞 Issue

Names or nicknames starting with a number always get cured to `ReVanced member`

## ⚙ Reproduce

1. Run the bot
2. Have an account in the same server with the bot
3. Nickname that account to start with a number

## 🛠 Solution

*No response.*

## ⚠ Additional context

*No response.*

**Comment by oSumAtrIX** [comment]
This is intended design

https://github.com/ReVanced/revanced-discord-bot/blob/21dd21c3771957246915956760fae328bf5ebad8/src/utils/decancer.rs#L34

**Comment by PalmDevs** [comment]
> This is intended design

Why? This disallows names like `5L V8 Engine` (an actual name someone wanted to change to).

**Comment by oSumAtrIX** [comment]
Because 5L V8 Engine is a silly name for a username on Discord.

**Comment by PalmDevs** [comment]
> Because 5L V8 Engine is a silly name for a username on Discord. 

Not a problem for us, we can't we have fun?

**Comment by oSumAtrIX** [comment]
The sole purpose of most usernames that have a number in front of them, are used to push you to the top of the members list. This is mitigated.
