### ISSUE TITLE
problem: confusing bot response 

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-discord-bot#77]
## 🐞 Issue

I believe that the 'Regarding your question' section in this response isn't grammatically correct and confusing in general.

![SmartSelect_20231008_235559_Discord.jpg](https://github.com/ReVanced/revanced-discord-bot/assets/84587632/ce96c4db-9f9d-4774-9598-d279620b1515)

**Comment by oSumAtrIX** [comment]
This is already updated but not deployed: https://github.com/ReVanced/revanced-discord-bot/blob/main/configuration.revanced.json#L142
