### ISSUE TITLE
feat: helpful links

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-discord-bot#79]
## 🐞 Issue

some links are frequently used and supporters needs copy/paste them often

## ❗ Solution

add a few slash commands to make it post some links, including

- link to revanced-patches issue creation page
- link to (re)vanced microG
- link to latest revanced manager release

## ❓ Motivation

Apart from solving the aforementioned issue, this can make the response more authentic as it has the official revanced symbol.

## ⚠ Additional context

This was inspired by the Sigma's (aka Ligma's) `>>seal` feature, which would respond a link to the latest seal release

**Comment by oSumAtrIX** [comment]
The last two points are available in #help which you can link or use ?dl/?manager
